# Generated by Django 4.0.5 on 2022-07-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_child_fiction_horror_nonfiction_urdu_book_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiction',
            name='image_url',
        ),
        migrations.AddField(
            model_name='fiction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
