# Generated by Django 4.0.5 on 2022-07-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_fiction_image_url_fiction_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='child',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='horror',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='nonfiction',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='urdu',
            name='image_url',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='child',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='horror',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='nonfiction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='urdu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
